{% set name = "dbt-postgres" %}
{% set version = "1.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/dbt_postgres-{{ version }}.tar.gz
  sha256: b0574e9e1e66d8a5cd627b1d464ec0278eef7342f0b5babe4f987eee9d02a143

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8.0
    - hatchling
    - pip
  run:
    # Note: psycopg2-binary is noarch, and works also for linux, so instead of adding
    # an os-dependent requirement, we instead use psycopg2-binary for simplicity.
    - python >=3.8.0
    - psycopg2-binary >=2.9,<3.0
    - dbt-adapters >=0.1.0a1,<2.0
    - dbt-core >=1.8.0a1
    - dbt-common >=0.1.0a1,<2.0
    - agate >=1.0,<2.0

test:
  imports:
    - dbt.adapters.postgres
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/dbt-labs/dbt-postgres
  summary: The dbt-postgres package contains all of the code enabling dbt to work with a Postgres database.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - maresb
    - rxm7706
